(function(){"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],Engine=window.EHSComplianceEngine,Guidance=window.EHSComplianceGuidance,Workflow=window.EHSComplianceWorkflow,Exporter=window.EHSComplianceExport,Analytics=window.EhsComplianceAnalytics,KEY="ehs-sil-compliance-v1.2",EXPORT_CAPABILITY="compliance_excel_export",FREE_PREVIEW_LIMIT=6;let step=0,regulations=[],rules=[],changes=[],results=[],databaseMeta={},usageMode="user",memberHasFullAccess=false,dataReady=false,state={profile:{},evaluations:{},selected:{},addedUpdates:[],updatedAt:""};
const specialOperationTags=["涉及动火作业","涉及受限空间作业","涉及高处作业","涉及吊装作业","涉及临时用电","涉及盲板抽堵","涉及断路或动土作业"];
const options={enterpriseTypes:["危险化学品生产企业","危险化学品经营企业","危险化学品使用企业","危险化学品储存企业","一般化工企业","制药企业","机械制造企业","电子制造企业","食品加工企业","仓储物流企业","其他工贸企业"],industries:["化学原料和化学制品制造","石油化工","医药制造","通用设备制造","专用设备制造","金属制品","电子设备制造","食品制造","仓储物流","其他"],riskTags:["构成危险化学品重大危险源","涉及易燃易爆场所","涉及重点监管危险化学品","涉及重点监管危险化工工艺","涉及特殊作业","存在职业病危害","产生废水","产生废气","产生工业噪声","产生一般固体废物或危险废物","设置环保治理设施","涉及消防重点部位","使用承包商","其他高风险活动"],specialOperationTypes:specialOperationTags,hazardousActivities:["危化品生产","危化品经营","危化品使用","危化品储存","危化品进口"],hazardousWasteActivities:["危废产生","危废暂存","危废自行利用","危废处置","危废填埋"],specialEquipmentTypes:["锅炉","压力容器","压力管道","气瓶","电梯","起重机械","场（厂）内专用机动车辆"],industryAttributes:["化工属性","石油化工属性"],managementCommitments:["自愿采纳ISO 45001","自愿采纳ISO 14001","自愿采纳其他标准"]};
function escape(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
Object.assign(options,Guidance.profileGroups);
function renderChoices(){for(const [id,vals] of Object.entries(options))$("#"+id).innerHTML=vals.map(v=>`<label class="choice"><input type="checkbox" name="${id}" value="${escape(v)}"><span>${escape(v)}</span></label>`).join("");}
function profile(){const form=new FormData($("#profileForm")),p={companyName:form.get("companyName")||"",province:form.get("province")||"",city:form.get("city")||"",scale:form.get("scale")||"",ownership:form.get("ownership")||"",answers:{...(state.profile.answers||{})},legacyEnvironmentUnknown:state.profile.legacyEnvironmentUnknown||false};for(const id of Object.keys(options))p[id]=form.getAll(id);return p;}
function setStep(n){step=n;$$('.form-step').forEach((el,i)=>el.classList.toggle('active',i===n));$$('.step-dot').forEach((el,i)=>el.classList.toggle('active',i<=n));$('#prevBtn').disabled=n===0;$('#nextBtn').classList.toggle('hidden',n===2);$('#identifyBtn').classList.toggle('hidden',n!==2);}
function validateStep(){if(step===0&&!$('#profileForm').reportValidity())return false;if(step===1&&!$$('[name=enterpriseTypes]:checked').length){show('请至少选择一个企业类型。','error');return false;}return true;}
function show(msg,type='ok'){const el=$('#feedback');el.textContent=msg;el.className=`feedback show ${type}`;setTimeout(()=>el.classList.remove('show'),7000);}
function save(){state.profile=profile();state.updatedAt=new Date().toISOString();if(usageMode==='example')return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{show('浏览器存储不可用，修改暂存在本页；离开前请导出项目。','error');}}
function migrateProfile(p){const riskTags=p.riskTags||[],legacyOperations=riskTags.filter(x=>specialOperationTags.includes(x)),legacyEnvironment=riskTags.includes("产生废水、废气或噪声");p.riskTags=riskTags.filter(x=>!specialOperationTags.includes(x)&&x!=="产生废水、废气或噪声");if(legacyOperations.length){p.riskTags.push("涉及特殊作业");p.specialOperationTypes=[...new Set([...(p.specialOperationTypes||[]),...legacyOperations])];}if(legacyEnvironment)p.legacyEnvironmentUnknown=true;p.riskTags=[...new Set(p.riskTags)];return p;}
function restore(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(!saved)return;state={profile:{},evaluations:{},selected:{},addedUpdates:[],updatedAt:'',...saved};state.profile=migrateProfile(state.profile);for(const no of state.addedUpdates||[]){const c=changes.find(x=>x.documentNo===no);if(c&&!regulations.some(r=>r.documentNo===no))regulations.push(updateRecord(c));}for(const [k,v] of Object.entries(state.profile)){if(Array.isArray(v))v.forEach(x=>{const el=$(`[name="${k}"][value="${CSS.escape(x)}"]`);if(el)el.checked=true;});else{const el=$(`[name="${k}"]`);if(el)el.value=v;}}if(state.profile.companyName&&state.profile.province){run();show('已恢复本地保存的数据。');}}catch(e){console.warn('Local data restore failed',e);}}
function run(scroll=true){if(!dataReady){show('法规数据尚未完整加载，请稍后重试。','error');return;}const p=profile();if(!p.companyName||!p.province){setStep(0);$('#profileForm').reportValidity();return;}const facts=Engine.profileFacts(p),permit=['排污许可重点管理','排污许可简化管理','排污登记管理'].filter(x=>facts.has(x));if(permit.length>1){$('#profileError').textContent='请按单一排污单位建立画像，排污管理类别只能选一项。';setStep(2);return;}$('#profileError').textContent='';results=Engine.identify(regulations,p,{rules});results.forEach(r=>{if(state.selected[r.id]===undefined)state.selected[r.id]=true;const e=state.evaluations[r.id],signature=[r.name,r.documentNo,r.guidanceVersion||'1.5'].join('|');if(e){if(e.judgment&&e.judgment!=='待评价'&&e.recordVersion!==signature)e.needsReassessment=true;e.recordVersion=signature;}});save();$('#initialState').classList.add('hidden');$('#resultArea').classList.remove('hidden');renderAll();if(Analytics)Analytics.track('result_generated',usageMode);if(scroll)window.scrollTo({top:document.querySelector('.results').offsetTop-12,behavior:'smooth'});}
function badge(v){const m={"明确适用":"clear","条件适用":"condition","建议复核":"review","现行有效":"current","即将实施":"upcoming","已发布待实施":"upcoming","已废止":"expired","待核实":"pending"};return `<span class="badge badge-${m[v]||'pending'}">${escape(v)}</span>`;}
function renderStats(){const count=v=>results.filter(r=>r.applicability===v).length,selected=results.filter(r=>state.selected[r.id]),evaluated=selected.filter(r=>evalFor(r.id).judgment!=='待评价').length,coverage=selected.length?Math.round(evaluated/selected.length*100):0,overdue=selected.filter(r=>evaluationStatus(evalFor(r.id)).startsWith('已逾期')).length,local=results.filter(r=>r.applicabilityType==='地方要求').length;$('#stats').innerHTML=[[count('明确适用'),'正式匹配'],[count('建议复核'),'建议复核'],[`${coverage}%`,'评价覆盖率'],[overdue,'逾期整改'],[results.filter(r=>r.computedStatus==='即将实施').length,'即将实施'],[local,'地方要求']].map(x=>`<div class="stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');}
function preview(list){return memberHasFullAccess?list:list.slice(0,FREE_PREVIEW_LIMIT);}
function renderSummary(){const clear=results.filter(r=>r.applicability==='明确适用').length,conditional=results.filter(r=>r.applicability==='条件适用').length,review=results.filter(r=>r.applicability==='建议复核').length,clauses=results.reduce((n,r)=>n+r.matchedClauses.length,0);$('#summaryText').textContent=`识别 ${results.length} 项法规/标准，自动整理 ${clauses} 组条款要求。${clear} 项画像范围已匹配，${conditional} 项有适用条件，${review} 项仍缺范围信息或来源核验。条款组不是独立法规条数。`;$('#summaryTags').innerHTML=[[clear,'明确适用'],[conditional,'条件适用'],[review,'待补充/核验'],[clauses,'条款要求']].map(([n,label])=>`<span class="summary-tag">${n} ${label}</span>`).join('');const notice=$('#previewNotice');notice.textContent=memberHasFullAccess?`工具箱会员权益已验证：当前显示全部 ${results.length} 条结果，可导出完整结构化 Excel。`:`免费版显示完整摘要和前 ${Math.min(FREE_PREVIEW_LIMIT,results.length)} 条结果；工具箱会员可查看全部 ${results.length} 条并导出四表 Excel。`;notice.classList.toggle('member-active',memberHasFullAccess);renderGuidance();}
function renderGuidance(){
  const p=profile(),questions=Guidance.clarify(results,p),facts=Engine.profileFacts(p);
  if(p.legacyEnvironmentUnknown)for(const fact of ['产生废水','产生废气','产生工业噪声'])if(!facts.has(fact)&&!p.answers[fact])questions.unshift({fact,regulations:['旧画像环境选项需区分，未自动推断三者都有']});
  $('#clarificationCount').textContent=questions.length?`${questions.length} 个范围信息可补充`:'当前已匹配项目没有额外范围追问';
  const shown=questions.slice(0,8);
  $('#clarificationQuestions').innerHTML=shown.map(q=>`<label class="clarify-item"><span>是否${escape(q.fact)}？<small>${escape(q.regulations.slice(0,2).join('；'))}${q.regulations.length>2?`等 ${q.regulations.length} 项`:''}</small></span><select data-clarify="${escape(q.fact)}" aria-label="是否${escape(q.fact)}"><option value="unknown">不确定 / 未填写</option><option value="yes" ${p.answers[q.fact]==='yes'?'selected':''}>是</option><option value="no">否</option></select></label>`).join('')+(questions.length>8?'<p>先回答以上问题，系统会继续展示相关追问。不确定的项目可以保留。</p>':'');
  const answers=Object.entries(p.answers).filter(([,v])=>['yes','no'].includes(v));
  $('#answeredFacts').classList.toggle('hidden',!answers.length);
  $('#answeredFacts').innerHTML=answers.length?`<summary>已补充 ${answers.length} 项（可修改）</summary>`+answers.map(([fact,value])=>`<label class="clarify-item"><span>${escape(fact)}</span><select data-clarify="${escape(fact)}"><option value="unknown">不确定</option><option value="yes" ${value==='yes'?'selected':''}>是</option><option value="no" ${value==='no'?'selected':''}>否</option></select></label>`).join(''):'';
  $$('[data-clarify]').forEach(el=>el.onchange=()=>{if(el.value==='no')$$('#profileForm input[type=checkbox]').filter(x=>x.value===el.dataset.clarify).forEach(x=>x.checked=false);state.profile.answers={...(state.profile.answers||{}),[el.dataset.clarify]:el.value};if(Analytics)Analytics.track('profile_refined',usageMode);run(false);});
  $('#coverageItems').innerHTML=Guidance.coverage(results,p).map(c=>`<div><strong>${escape(c.name)}</strong><span>${c.matched} 项匹配${c.detailed!==undefined?` / ${c.detailed} 项有条款卡`:''}</span>${c.warning?`<small>${escape(c.warning)}</small>`:''}</div>`).join('');
  const retired=Object.keys(state.evaluations).filter(id=>!results.some(r=>r.id===id)&&state.evaluations[id].judgment&&state.evaluations[id].judgment!=='待评价');
  $('#versionNotice').textContent=`来源核验、企业适用性、实际符合性分别记录。${retired.length?`有 ${retired.length} 项历史评价因画像/版本变化不在本次结果中，已保留在本地及项目文件，未移植为新法规结论。`:''}`;
}
function filtered(){const q=$('#search').value.trim().toLowerCase(),l=$('#levelFilter').value,a=$('#appFilter').value,s=$('#statusFilter').value;return results.filter(r=>(!q||[r.name,r.documentNo,r.reasons.join(' ')].join(' ').toLowerCase().includes(q))&&(!l||r.type===l)&&(!a||r.applicability===a)&&(!s||r.computedStatus===s));}
function evalFor(id){return state.evaluations[id]||(state.evaluations[id]={evidence:'',judgment:'待评价',gap:'',action:'',owner:'',due:'',completedAt:'',verification:'',reviewDate:'',conversion:'未开始',primaryDepartment:'',cooperatingDepartments:'',evidenceRequirement:''});}
function requiredMissing(e){return Workflow.requiredMissing(e);}
function evaluationStatus(e){if(e.needsReassessment)return '版本已变，需重评';if(['符合','不适用'].includes(e.judgment)&&requiredMissing(e).length)return '待补充判定依据';return Workflow.evaluationStatus(e,Engine.cnToday(),Engine.daysBetween);}
function validateEvaluations(){const bad=results.filter(r=>state.selected[r.id]&&requiredMissing(evalFor(r.id)).length);if(!bad.length)return true;const first=bad[0],missing=requiredMissing(evalFor(first.id));show(`“${first.name}”缺少：${missing.join('、')}。请补充后再导出。`,'error');return false;}
function renderLedger(){
  const rows=preview(filtered());
  $('#focusedRequirement').classList.add('hidden');$('#focusedRequirement').innerHTML='';
  $('#quickResults').innerHTML=rows.map(r=>`<button type="button" class="quick-result" data-open-requirements="${r.id}"><strong>${escape(r.name)}</strong><span>${escape(r.applicability)} · ${r.matchedClauses.length} 组已整理条款</span><em>查看条款、要求与证据 →</em></button>`).join('');
  $('#ledgerBody').innerHTML=rows.length?rows.map((r,i)=>{
    const e=evalFor(r.id),departments=r.suggestedDepartment||[],checks=e.checks||{};
    const cards=r.matchedClauses.map(c=>{const check=checks[c.id]||{};return `<article class="clause-card"><h4>${escape(c.reference)}</h4><p>${escape(c.summary)}</p><p><strong>建议动作：</strong>${escape(c.action)}</p><p><strong>准备证据：</strong>${escape((c.evidence||[]).join('；'))}</p><a href="${escape(c.sourceUrl||r.sourceUrl)}" target="_blank" rel="noopener">官方条文 ↗</a><div class="evidence-check"><label>证据登记（非合规结论）<select data-check-state="${escape(c.id)}" data-id="${r.id}"><option value="unknown">尚未提供</option><option value="provided" ${check.state==='provided'?'selected':''}>已提供证据索引</option><option value="missing" ${check.state==='missing'?'selected':''}>已发现缺项</option></select></label><label>证据名称 / 日期 / 缺项说明<textarea maxlength="2000" data-check-note="${escape(c.id)}" data-id="${r.id}" placeholder="填写内部文件索引，不需要上传文件">${escape(check.note||'')}</textarea></label></div></article>`;}).join('');
    return `<tr><td><input class="row-select" data-id="${r.id}" type="checkbox" ${state.selected[r.id]?'checked':''}></td><td>${i+1}</td><td>${escape(r.type)}</td><td class="reg-name">${escape(r.name)}<small>${r.matchedClauses.length? r.matchedClauses.length+' 组条款已整理':'条款卡尚未覆盖'}</small></td><td>${escape(r.documentNo)}</td><td>${badge(r.computedStatus)}<small>${escape(r.sourceVerification)}</small></td><td>${escape(r.effectiveDate||'—')}</td><td>${badge(r.applicability)}<small>${escape(r.scopeApplicability||'')}</small></td><td class="reason">${escape(r.reasons.join('；'))}</td><td>${escape(e.primaryDepartment||departments[0]||'待指定')}</td><td><input class="review-date" data-id="${r.id}" type="date" value="${escape(e.reviewDate)}"></td><td>${badge(Engine.reviewReminder(e.reviewDate))}</td><td><a href="${escape(r.sourceUrl)}" target="_blank" rel="noopener">${escape(r.sourceName)}</a></td><td><button class="btn btn-secondary detail-btn" data-id="${r.id}">条款与要求</button></td></tr><tr class="detail-row" data-detail="${r.id}"><td colspan="14"><div class="auto-guidance"><h3>自动生成的适用性评价与落实清单</h3><p>${escape(r.evaluationDraft)}</p>${e.needsReassessment?'<p class="version-warning">法规版本或规则已更新，历史评价已保留，需按本版本重新评价。</p>':''}<p class="evidence-progress">${escape(Guidance.evidenceProgress(r,checks).label)}</p>${cards||`<p>${escape(r.requirementSummary)}</p>`}${r.pendingClauses.length?`<p>另有 ${r.pendingClauses.length} 组条件条款可在上方补充画像后判断。</p>`:''}</div><div class="detail-box"><div><dt>主责部门</dt><dd><input data-detail-edit="primaryDepartment" data-id="${r.id}" value="${escape(e.primaryDepartment||departments[0]||'')}"></dd></div><div><dt>协同部门</dt><dd><input data-detail-edit="cooperatingDepartments" data-id="${r.id}" value="${escape(e.cooperatingDepartments||departments.slice(1).join('、'))}"></dd></div><div><dt>转化落实情况</dt><dd><select data-detail-edit="conversion" data-id="${r.id}">${['未开始','制度修订中','已转化','不适用'].map(v=>`<option ${e.conversion===v?'selected':''}>${v}</option>`).join('')}</select></dd></div><div><dt>证据要求（自动建议可编辑）</dt><dd><textarea data-detail-edit="evidenceRequirement" data-id="${r.id}">${escape(e.evidenceRequirement||r.evidenceRequirement||'')}</textarea></dd></div><div><dt>结果反馈</dt><dd><a href="../feedback.html?type=content_issue&amp;tool=compliance-identification&amp;entry=result&amp;id=${encodeURIComponent(r.id)}&amp;toolVersion=1.6.0&amp;dataVersion=1.6.0" data-feedback-open data-feedback-tool="compliance-identification" data-feedback-entry="result" data-public-entry-id="${escape(r.id)}" data-tool-version="1.6.0" data-data-version="1.6.0">这条结果有疑问？反馈</a></dd></div></div></td></tr>`;
  }).join(''):'<tr><td colspan="14" class="empty">没有匹配结果，请调整画像或筛选条件。</td></tr>';
  bindTable();
  $$('[data-open-requirements]').forEach(el=>el.onclick=()=>{const id=el.dataset.openRequirements;renderLedger();const r=results.find(x=>x.id===id),row=$(`[data-detail="${id}"]`),panel=$('#focusedRequirement');panel.innerHTML=`<div class="focused-head"><h2>${escape(r.name)}</h2><button type="button" class="btn btn-secondary" id="closeRequirements">收起条款</button></div>`+row.querySelector('.auto-guidance').outerHTML;panel.classList.remove('hidden');$('#closeRequirements').onclick=()=>panel.classList.add('hidden');bindEvidenceChecks();panel.scrollIntoView({behavior:'smooth',block:'start'});if(Analytics)Analytics.track('detail_opened',usageMode);});
  bindEvidenceChecks();
}
function bindEvidenceChecks(){
  $$('[data-check-state],[data-check-note]').forEach(el=>{const update=event=>{
    const e=evalFor(el.dataset.id),id=el.dataset.checkState||el.dataset.checkNote;
    e.checks=e.checks||{};e.checks[id]=e.checks[id]||{};e.checks[id][el.dataset.checkState?'state':'note']=el.value;save();
    const r=results.find(x=>x.id===el.dataset.id);
    el.closest('.auto-guidance').querySelector('.evidence-progress').textContent=Guidance.evidenceProgress(r,e.checks).label;
    if(Analytics&&event.type==='change')Analytics.track('evidence_recorded',usageMode);
  };el.onchange=update;if(el.dataset.checkNote)el.oninput=update;});
}
function renderEvaluation(){const selected=preview(results.filter(r=>state.selected[r.id]));$('#evaluationBody').innerHTML=selected.map(r=>{const e=evalFor(r.id),missing=requiredMissing(e),rowClass=e.judgment==='不符合'?'row-noncompliant':e.judgment==='基本符合'?'row-partial':'',required=missing.length?'field-required':'';return `<tr class="${rowClass}"><td class="reg-name">${escape(r.name)}<br><small>${escape(r.documentNo)}</small></td><td>${escape(r.requirementSummary)}<small>${escape(r.evaluationDraft)}</small>${e.needsReassessment?'<strong class="version-warning">版本已变，历史判定需重评</strong>':''}</td><td><textarea data-edit="evidence" data-id="${r.id}">${escape(e.evidence)}</textarea></td><td><select data-edit="judgment" data-id="${r.id}">${['待评价','符合','基本符合','不符合','不适用'].map(v=>`<option ${e.judgment===v?'selected':''}>${v}</option>`).join('')}</select></td><td><textarea class="${required&&!e.gap?required:''}" data-edit="gap" data-id="${r.id}">${escape(e.gap)}</textarea></td><td><textarea class="${required&&!e.action?required:''}" data-edit="action" data-id="${r.id}">${escape(e.action)}</textarea></td><td><input class="${required&&!e.owner?required:''}" data-edit="owner" data-id="${r.id}" value="${escape(e.owner)}"></td><td><input class="${required&&!e.due?required:''}" type="date" data-edit="due" data-id="${r.id}" value="${escape(e.due)}"></td><td><input type="date" data-edit="completedAt" data-id="${r.id}" value="${escape(e.completedAt)}"></td><td><textarea data-edit="verification" data-id="${r.id}">${escape(e.verification)}</textarea></td><td>${badge(evaluationStatus(e))}${missing.length?`<small class="validation-note">需补：${escape(missing.join('、'))}</small>`:''}</td></tr>`}).join('');bindEdits();}
function updateRecord(c){return {matchedClauses:[],pendingClauses:[],missingFacts:[],evidenceRequirement:'',sourceVerification:'候选版本尚待核验',evaluationDraft:'新增候选条目尚未形成条款检查清单，不自动判定适用或符合。',id:`UPDATE-${c.documentNo.replace(/\W/g,'')}`,name:c.name,documentNo:c.documentNo,type:'行业标准',levelRank:4,issuingAuthority:c.source,status:'已发布待实施',publishDate:c.publishDate,effectiveDate:c.effectiveDate,sourceUrl:c.sourceUrl,sourceName:c.source,sourceType:c.source,regions:['全国'],applicabilityType:'条件触发',verificationStatus:'待复核',complianceEnabled:true,changeType:c.changeType,replaces:[],requirementSummary:'新发布候选法规，适用性与具体条款需人工确认。',applicableClauses:'需人工确认',suggestedDepartment:['EHS部门'],reasons:['用户从法规动态跟踪加入台账；适用性尚待人工复核'],applicability:'建议复核',computedStatus:Engine.implementationStatus({verificationStatus:'待复核',status:'已发布待实施',effectiveDate:c.effectiveDate},Engine.cnToday())};}
function addUpdate(no){const c=changes.find(x=>x.documentNo===no);if(!c||state.addedUpdates.includes(no))return;const r=updateRecord(c);state.addedUpdates.push(no);regulations.push(r);results.push(r);state.selected[r.id]=true;save();renderAll();show(`已将“${c.name}”作为待复核记录加入台账。`);}
function renderTracking(){const current=results.filter(r=>r.changeType&&r.changeType!=='无变化'||r.computedStatus==='即将实施'),known=new Set(results.map(r=>r.documentNo)),incoming=changes.map(updateRecord),list=preview([...current,...incoming.filter(r=>!current.some(x=>x.documentNo===r.documentNo))]);$('#trackingBody').innerHTML=list.map(r=>{const inLedger=known.has(r.documentNo),distance=Engine.implementationDistanceLabel(r.effectiveDate),days=Engine.daysBetween(Engine.cnToday(),r.effectiveDate),e=evalFor(r.id),conversionDone=['已转化','不适用'].includes(e.conversion),urgency=days!==null&&days<=0&&!conversionDone?'track-danger':days!==null&&days<30?'track-danger':days!==null&&days<=90?'track-warning':'track-ok';return `<tr><td>${escape(r.lastVerifiedAt||r.publishDate||'—')}</td><td>${escape(r.sourceName)}</td><td class="reg-name">${escape(r.name)}</td><td>${escape(r.changeType||'待复核')}</td><td>${escape((r.replaces||[]).join('、')||'—')}</td><td>${escape(r.documentNo)}</td><td>${escape(r.effectiveDate||'—')}</td><td>${badge(r.computedStatus)}</td><td class="${urgency}">${escape(distance)}</td><td>需要人工评估</td><td>核对适用条款并更新内部文件</td><td>${escape(e.owner||'待指定')}</td><td>${inLedger?'<span class="badge badge-current">已在台账</span>':`<button class="btn btn-secondary add-update" data-no="${escape(r.documentNo)}">加入台账</button>`}</td><td><a class="source-link" href="${escape(r.sourceUrl)}" target="_blank" rel="noopener">查看</a></td></tr>`}).join('');$$('.add-update').forEach(el=>el.onclick=()=>addUpdate(el.dataset.no));}
function renderAll(){renderStats();renderSummary();renderLedger();renderEvaluation();renderTracking();}
function bindTable(){$$('.row-select').forEach(el=>el.onchange=()=>{state.selected[el.dataset.id]=el.checked;save();renderStats();renderEvaluation();renderTracking();});$$('.review-date').forEach(el=>el.onchange=()=>{evalFor(el.dataset.id).reviewDate=el.value;save();renderLedger();});$$('.detail-btn').forEach(el=>el.onclick=()=>{document.querySelector(`[data-detail="${el.dataset.id}"]`).classList.toggle('open');if(Analytics)Analytics.track('detail_opened',usageMode);});$$('[data-detail-edit]').forEach(el=>el.onchange=()=>{evalFor(el.dataset.id)[el.dataset.detailEdit]=el.value;save();renderLedger();renderTracking();});}
function bindEdits(){$$('[data-edit]').forEach(el=>el.onchange=()=>{evalFor(el.dataset.id)[el.dataset.edit]=el.value;if(el.dataset.edit==='judgment')evalFor(el.dataset.id).needsReassessment=false;save();renderStats();renderEvaluation();});}
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function exportExcel(){if(!window.ExcelJS||!Exporter){show('Excel 组件加载失败，请刷新后重试。','error');return;}const selected=results.filter(r=>state.selected[r.id]);if(!selected.length){show('请至少勾选一条法规。','error');return;}if(!validateEvaluations())return;try{const wb=Exporter.buildWorkbook(window.ExcelJS,{profile:profile(),selected,evaluations:state.evaluations,meta:databaseMeta,today:Engine.cnToday(),statusFor:evaluationStatus,reminderFor:d=>Engine.reviewReminder(d),distanceFor:d=>Engine.implementationDistanceLabel(d)}),buf=await wb.xlsx.writeBuffer(),name=profile().companyName.replace(/[\\/:*?"<>|]/g,'_');download(buf,`EHS合规识别台账_${name}_${Engine.cnToday()}.xlsx`,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');if(Analytics)Analytics.track('excel_exported',usageMode);show('Excel 已生成，包含四个可直接维护的工作表。');}catch(e){console.error(e);show('Excel 生成失败，请刷新后重试。','error');}}
function exportProject(){if(!validateEvaluations())return;const project=Workflow.createProject({profile:profile(),selected:state.selected,evaluations:state.evaluations,addedUpdates:state.addedUpdates,updatedAt:new Date().toISOString()});download(JSON.stringify(project,null,2),`EHS合规项目_${(project.profile.companyName||'未命名').replace(/[\\/:*?"<>|]/g,'_')}_${Engine.cnToday()}.ehsproject.json`,'application/json');show('项目文件已导出，仅包含当前浏览器中的项目数据。');}
function importProject(file){if(file.size>3*1024*1024){show('项目文件超过3MB，请检查文件是否正确。','error');return;}const reader=new FileReader();reader.onload=()=>{try{const p=Workflow.validateProject(JSON.parse(reader.result));if(!confirm('导入将覆盖当前浏览器中的项目数据，是否继续？'))return;state={profile:p.profile,evaluations:p.evaluations,selected:Object.fromEntries(p.selectedRegulationIds.map(id=>[id,true])),addedUpdates:p.addedUpdates||[],updatedAt:p.updatedAt||''};localStorage.setItem(KEY,JSON.stringify(state));location.reload();}catch(e){show(`项目导入失败：${e.message}`,'error');}};reader.onerror=()=>show('项目文件读取失败，请重新选择。','error');reader.readAsText(file);}
function openMemberGate(){const modal=$('#memberExportModal');modal.classList.remove('hidden');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');$('#memberLoginLink').focus();if(Analytics)Analytics.track('vip_prompt_viewed',usageMode);}
function closeMemberGate(){const modal=$('#memberExportModal');modal.classList.add('hidden');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}
async function withExportCapability(action){const hint=$('#membershipHint');if(hint)hint.textContent='正在验证会员权益…';try{if(window.EhsSilVip&&await window.EhsSilVip.hasCapability(EXPORT_CAPABILITY,true)){memberHasFullAccess=true;if(hint)hint.textContent='工具箱会员权益已验证，可查看全部结果并下载专业文件';renderAll();return action();}}catch(e){console.warn('Membership capability check failed',e);}memberHasFullAccess=false;const status=window.EhsSilVip?.getState?.().status;if(!window.EhsSilVip||status==='error'||status==='checking'){if(hint)hint.textContent='会员权益暂未确认，请重试；免费预览与本地数据保留';renderAll();show('暂时无法确认权益，请稍后再次点击重试。此状态不代表过期，不需要重新购买。','error');return;}if(hint)hint.textContent='在线识别免费；完整结果、专业 Excel 与项目文件为会员权益';renderAll();openMemberGate();}
async function refreshMembershipHint(){const previous=memberHasFullAccess,hint=$('#membershipHint');if(!hint)return;try{const session=window.EhsSilVip?await window.EhsSilVip.getSession(true):null;memberHasFullAccess=Boolean(session&&session.active&&Array.isArray(session.capabilities)&&session.capabilities.includes(EXPORT_CAPABILITY));hint.textContent=session?.status==='error'||!session?'会员权益暂未确认，请重试；免费预览与本地数据保留':memberHasFullAccess?'工具箱会员权益已验证，可查看全部结果并下载专业文件':'在线识别免费；完整结果、专业 Excel 与项目文件为会员权益';hint.classList.toggle('member-active',memberHasFullAccess);if(results.length&&previous!==memberHasFullAccess)renderAll();}catch(e){memberHasFullAccess=false;hint.textContent='在线识别免费；完整结果、专业 Excel 与项目文件为会员权益';if(results.length&&previous!==memberHasFullAccess)renderAll();}}
async function init(){
  renderChoices();
  try{
    const get=path=>fetch(`${path}?v=1.6.0`).then(r=>{if(!r.ok)throw Error(path);return r.json()});
    const [formal,candidates,ruleData,changeData,environment,safety,corrections]=await Promise.all([get('../data/compliance/laws.v1.json'),get('../data/compliance/candidates.v1.json'),get('../data/compliance/rules.v1.json'),get('../data/compliance/changes.v1.json'),get('../data/compliance/environment.v1.6.json'),get('../data/compliance/safety.v1.6.json'),get('../data/compliance/scope-corrections.v1.6.json')]);
    const baseRules=new Map(ruleData.rules.map(r=>[r.regulationId,r]));
    for(const r of corrections.rules)baseRules.set(r.regulationId,{...baseRules.get(r.regulationId),...r});
    const merged=Guidance.mergeCatalog([...formal.records,...candidates.records],[...baseRules.values()],[environment,safety]);
    regulations=merged.records;rules=merged.rules;changes=(changeData.candidates||[]).filter(c=>!regulations.some(r=>r.documentNo===c.documentNo));
    const active=regulations.filter(r=>r.complianceEnabled&&Engine.implementationStatus(r,Engine.cnToday())!=='已废止');
    databaseMeta={schemaVersion:'1.6.0',total:active.length,verified:active.filter(r=>r.verificationStatus==='已核验').length,latestVerifiedAt:[formal.latestVerifiedAt,environment.checkedAt,safety.checkedAt].sort().at(-1)};
    $('#databaseCount').textContent=databaseMeta.total;$('#verifiedCount').textContent=databaseMeta.verified;$('#latestVerifiedAt').textContent=databaseMeta.latestVerifiedAt;
    dataReady=true;restore();refreshMembershipHint();
  }catch(e){$('#initialState').innerHTML='<strong>法规数据加载不完整</strong><span>为避免用旧法规生成新结论，本次已停止识别。请刷新后重试。</span>';$('#identifyBtn').disabled=true;console.error(e);}
}
$('#nextBtn').onclick=()=>{if(validateStep())setStep(step+1)};$('#prevBtn').onclick=()=>setStep(step-1);$('#identifyBtn').onclick=()=>{usageMode='user';run();};$('#exampleBtn').onclick=()=>{usageMode='example';if(Analytics)Analytics.track('example_used','example');$('#companyName').value='淄博示例化工有限公司';$('#province').value='山东省';$('#city').value='淄博市';$$('#profileForm input[type=checkbox]').forEach(el=>el.checked=false);state.profile.answers={};const sample={enterpriseTypes:['危险化学品使用企业'],industries:['化学原料和化学制品制造'],riskTags:['涉及特殊作业','存在职业病危害','产生废水','产生废气','产生工业噪声','产生一般固体废物或危险废物'],specialOperationTypes:['涉及动火作业','涉及受限空间作业','涉及高处作业','涉及临时用电'],hazardousActivities:['危化品使用','危化品储存'],environmentalActivities:['排放工业废水','废水间接排放','排放VOCs','产生一般工业固体废物'],regulatoryAttributes:['排污许可重点管理'],workplaceActivities:['涉及有限空间','涉及特种作业人员'],hazardousWasteActivities:['危废产生','危废暂存'],specialEquipmentTypes:['压力容器'],industryAttributes:['化工属性']};Object.entries(sample).forEach(([name,values])=>values.forEach(v=>{const el=document.querySelector(`[name="${name}"][value="${v}"]`);if(el)el.checked=true;}));setStep(2);run();};$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active');});['search','levelFilter','appFilter','statusFilter'].forEach(id=>$('#'+id).oninput=renderLedger);$('#selectAll').onchange=e=>{preview(filtered()).forEach(r=>state.selected[r.id]=e.target.checked);save();renderAll();};$('#printBtn').onclick=()=>window.print();const requestExcelExport=()=>{if(Analytics)Analytics.track('export_clicked',usageMode);withExportCapability(exportExcel);};$('#exportBtn').onclick=requestExcelExport;$('#summaryExportBtn').onclick=requestExcelExport;$('#exportProjectBtn').onclick=()=>withExportCapability(exportProject);$('#importProjectBtn').onclick=()=>withExportCapability(()=>$('#projectFile').click());$('#projectFile').onchange=e=>{if(e.target.files[0])importProject(e.target.files[0]);e.target.value='';};$('#memberModalClose').onclick=closeMemberGate;$('#memberExportModal').onclick=e=>{if(e.target.id==='memberExportModal')closeMemberGate();};$('#memberLoginLink').onclick=()=>{if(Analytics)Analytics.track('vip_entry_clicked',usageMode);};$('#memberPlanetLink').onclick=()=>{if(Analytics)Analytics.track('knowledge_planet_clicked',usageMode);};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#memberExportModal').classList.contains('hidden'))closeMemberGate();});$('#clearBtn').onclick=()=>{if(confirm('确定清除本浏览器保存的企业画像和评价内容吗？')){localStorage.removeItem(KEY);location.reload();}};init();
})();
