(function(){"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],Engine=window.EHSComplianceEngine,KEY="ehs-sil-compliance-v1.1";let step=0,regulations=[],results=[],state={profile:{},evaluations:{},selected:{}};
const options={enterpriseTypes:["危险化学品生产企业","危险化学品经营企业","危险化学品使用企业","危险化学品储存企业","一般化工企业","制药企业","机械制造企业","电子制造企业","食品加工企业","仓储物流企业","其他工贸企业"],industries:["化学原料和化学制品制造","医药制造","通用设备制造","专用设备制造","金属制品","电子设备制造","食品制造","仓储物流","其他"],riskTags:["使用或储存危险化学品","构成危险化学品重大危险源","涉及易燃易爆场所","涉及重点监管危险化学品","涉及重点监管危险化工工艺","涉及动火作业","涉及受限空间作业","涉及高处作业","涉及吊装作业","涉及临时用电","涉及盲板抽堵","涉及断路或动土作业","使用特种设备","存在职业病危害","产生危险废物","设置环保治理设施","涉及消防重点部位","使用承包商","其他高风险活动"]};
function escape(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function renderChoices(){for(const [id,vals] of Object.entries(options))$("#"+id).innerHTML=vals.map(v=>`<label class="choice"><input type="checkbox" name="${id}" value="${escape(v)}"><span>${escape(v)}</span></label>`).join("");}
function profile(){const form=new FormData($("#profileForm")),p={companyName:form.get("companyName")||"",province:form.get("province")||"",city:form.get("city")||"",scale:form.get("scale")||"",ownership:form.get("ownership")||""};for(const id of Object.keys(options))p[id]=form.getAll(id);return p;}
function setStep(n){step=n;$$('.form-step').forEach((el,i)=>el.classList.toggle('active',i===n));$$('.step-dot').forEach((el,i)=>el.classList.toggle('active',i<=n));$('#prevBtn').disabled=n===0;$('#nextBtn').classList.toggle('hidden',n===2);$('#identifyBtn').classList.toggle('hidden',n!==2);}
function validateStep(){if(step===0&&!$('#profileForm').reportValidity())return false;if(step===1&&!$$('[name=enterpriseTypes]:checked').length){show('请至少选择一个企业类型。','error');return false;}return true;}
function show(msg,type='ok'){const el=$('#feedback');el.textContent=msg;el.className=`feedback show ${type}`;setTimeout(()=>el.classList.remove('show'),5000);}
function save(){state.profile=profile();localStorage.setItem(KEY,JSON.stringify(state));}
function restore(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(!saved)return;state={profile:{},evaluations:{},selected:{},...saved};for(const [k,v] of Object.entries(state.profile)){if(Array.isArray(v))v.forEach(x=>{const el=$(`[name="${k}"][value="${CSS.escape(x)}"]`);if(el)el.checked=true;});else{const el=$(`[name="${k}"]`);if(el)el.value=v;}}if(state.profile.companyName&&state.profile.province){run();show('已恢复本地保存的数据。');}}catch(e){console.warn('Local data restore failed',e);}}
function run(){const p=profile();if(!p.companyName||!p.province){setStep(0);$('#profileForm').reportValidity();return;}results=Engine.identify(regulations,p);results.forEach(r=>{if(state.selected[r.id]===undefined)state.selected[r.id]=true;});save();$('#initialState').classList.add('hidden');$('#resultArea').classList.remove('hidden');renderAll();window.scrollTo({top:document.querySelector('.results').offsetTop-12,behavior:'smooth'});}
function badge(v){const m={"明确适用":"clear","条件适用":"condition","建议复核":"review","现行有效":"current","即将实施":"upcoming","已发布待实施":"upcoming","已废止":"expired","待核实":"pending"};return `<span class="badge badge-${m[v]||'pending'}">${escape(v)}</span>`;}
function renderStats(){const count=v=>results.filter(r=>r.applicability===v).length,st=v=>results.filter(r=>r.computedStatus===v).length,local=results.filter(r=>r.applicabilityType==='地方要求').length,pending=results.filter(r=>r.verificationStatus!=='已核验').length;$('#stats').innerHTML=[[results.length,'识别结果'],[count('明确适用'),'明确适用'],[count('条件适用')+count('建议复核'),'条件/复核'],[st('即将实施'),'即将实施'],[local,'地方要求'],[pending,'待人工确认']].map(x=>`<div class="stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');}
function filtered(){const q=$('#search').value.trim().toLowerCase(),l=$('#levelFilter').value,a=$('#appFilter').value,s=$('#statusFilter').value;return results.filter(r=>(!q||[r.name,r.documentNo,r.reasons.join(' ')].join(' ').toLowerCase().includes(q))&&(!l||r.type===l)&&(!a||r.applicability===a)&&(!s||r.computedStatus===s));}
function evalFor(id){return state.evaluations[id]||(state.evaluations[id]={evidence:'',judgment:'待评价',gap:'',action:'',owner:'',due:'',status:'未开始',reviewDate:''});}
function renderLedger(){const rows=filtered();$('#ledgerBody').innerHTML=rows.length?rows.map((r,i)=>{const e=evalFor(r.id),rem=Engine.reviewReminder(e.reviewDate);return `<tr><td><input class="row-select" data-id="${r.id}" type="checkbox" ${state.selected[r.id]?'checked':''}></td><td>${i+1}</td><td>${escape(r.type)}</td><td class="reg-name">${escape(r.name)}</td><td>${escape(r.documentNo)}</td><td>${badge(r.computedStatus)}</td><td>${escape(r.effectiveDate||'—')}</td><td>${badge(r.applicability)}</td><td class="reason">${escape(r.reasons.join('；'))}</td><td>${escape((r.suggestedDepartment||[]).join('、'))}</td><td><input class="review-date" data-id="${r.id}" type="date" value="${escape(e.reviewDate)}"></td><td>${badge(rem)}</td><td><a class="source-link" href="${escape(r.sourceUrl)}" target="_blank" rel="noopener">${escape(r.sourceName)}</a></td><td><button class="btn btn-secondary detail-btn" data-id="${r.id}">展开</button></td></tr><tr class="detail-row" data-detail="${r.id}"><td colspan="14"><dl class="detail-box"><div><dt>要求摘要</dt><dd>${escape(r.requirementSummary||'待复核')}</dd></div><div><dt>适用条款/章节</dt><dd>${escape(r.applicableClauses||'需人工确认')}</dd></div><div><dt>核验状态</dt><dd>${escape(r.verificationStatus)} · ${escape(r.lastVerifiedAt||'未记录')}</dd></div></dl></td></tr>`}).join(''):`<tr><td colspan="14" class="empty"><strong>没有匹配结果</strong>请调整搜索或筛选条件。</td></tr>`;bindTable();}
function renderEvaluation(){const selected=results.filter(r=>state.selected[r.id]);$('#evaluationBody').innerHTML=selected.map(r=>{const e=evalFor(r.id);return `<tr><td class="reg-name">${escape(r.name)}<br><small>${escape(r.documentNo)}</small></td><td>${escape(r.applicableClauses||r.requirementSummary||'待人工确认')}</td><td><textarea data-edit="evidence" data-id="${r.id}">${escape(e.evidence)}</textarea></td><td><select data-edit="judgment" data-id="${r.id}">${['待评价','符合','基本符合','不符合','不适用'].map(v=>`<option ${e.judgment===v?'selected':''}>${v}</option>`).join('')}</select></td><td><textarea data-edit="gap" data-id="${r.id}">${escape(e.gap)}</textarea></td><td><textarea data-edit="action" data-id="${r.id}">${escape(e.action)}</textarea></td><td><input data-edit="owner" data-id="${r.id}" value="${escape(e.owner)}"></td><td><input type="date" data-edit="due" data-id="${r.id}" value="${escape(e.due)}"></td><td><select data-edit="status" data-id="${r.id}">${['未开始','进行中','待验证','已完成'].map(v=>`<option ${e.status===v?'selected':''}>${v}</option>`).join('')}</select></td></tr>`}).join('');bindEdits();}
function renderTracking(){const list=results.filter(r=>r.changeType&&r.changeType!=='无变化'||r.computedStatus==='即将实施');$('#trackingBody').innerHTML=list.map(r=>{const d=Engine.daysBetween(Engine.cnToday(),r.effectiveDate);return `<tr><td>${escape(r.lastVerifiedAt||'—')}</td><td>${escape(r.sourceName)}</td><td class="reg-name">${escape(r.name)}</td><td>${escape(r.changeType||'待复核')}</td><td>${escape((r.replaces||[]).join('、')||'—')}</td><td>${escape(r.documentNo)}</td><td>${escape(r.effectiveDate||'—')}</td><td>${badge(r.computedStatus)}</td><td>${d===null?'—':d}</td><td>需要人工评估</td><td>核对适用条款并更新内部文件</td><td>待指定</td><td>未开始</td><td><a class="source-link" href="${escape(r.sourceUrl)}" target="_blank" rel="noopener">查看</a></td></tr>`}).join('');}
function renderAll(){renderStats();renderLedger();renderEvaluation();renderTracking();}
function bindTable(){$$('.row-select').forEach(el=>el.onchange=()=>{state.selected[el.dataset.id]=el.checked;save();renderEvaluation();});$$('.review-date').forEach(el=>el.onchange=()=>{evalFor(el.dataset.id).reviewDate=el.value;save();renderLedger();});$$('.detail-btn').forEach(el=>el.onclick=()=>document.querySelector(`[data-detail="${el.dataset.id}"]`).classList.toggle('open'));}
function bindEdits(){$$('[data-edit]').forEach(el=>el.onchange=()=>{evalFor(el.dataset.id)[el.dataset.edit]=el.value;save();});}
function sheetHeader(ws,row){row.eachCell(c=>{c.font={bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1E3A5F'}};c.alignment={vertical:'middle',wrapText:true};});ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:{row:1,column:1},to:{row:1,column:row.cellCount}};}
async function exportExcel(){if(!window.ExcelJS){show('Excel 组件加载失败，请检查网络后重试。','error');return;}const selected=results.filter(r=>state.selected[r.id]);if(!selected.length){show('请至少勾选一条法规。','error');return;}try{const wb=new ExcelJS.Workbook();wb.creator='EHS-SIL';const p=profile();let ws=wb.addWorksheet('企业画像与使用说明');ws.addRow(['字段','内容']);Object.entries({企业名称:p.companyName,省份:p.province,城市:p.city,企业规模:p.scale,所有制:p.ownership,企业类型:p.enterpriseTypes.join('、'),行业:p.industries.join('、'),风险与活动:p.riskTags.join('、')}).forEach(x=>ws.addRow(x));ws.addRow([]);ws.addRow(['使用说明','本结果为初步识别，不构成法律意见或最终合规结论。']);sheetHeader(ws,ws.getRow(1));
ws=wb.addWorksheet('法规识别台账');ws.addRow(['序号','类别层级','法规或标准名称','文号/标准号','状态','发布日期','实施日期','发布机关','适用性结论','匹配原因','适用条款或章节','对应部门','下次评审日期','评审提醒','核验状态','官方来源']);selected.forEach((r,i)=>{const e=evalFor(r.id),row=ws.addRow([i+1,r.type,r.name,r.documentNo,r.computedStatus,r.publishDate,r.effectiveDate,r.issuingAuthority,r.applicability,r.reasons.join('；'),r.applicableClauses,(r.suggestedDepartment||[]).join('、'),e.reviewDate,Engine.reviewReminder(e.reviewDate),r.verificationStatus,{text:r.sourceName,hyperlink:r.sourceUrl}]);const reminder=row.getCell(14).value;row.getCell(14).fill={type:'pattern',pattern:'solid',fgColor:{argb:reminder==='已逾期'?'FFFECACA':reminder==='30日内到期'?'FFFEF3C7':'FFDCFCE7'}};});sheetHeader(ws,ws.getRow(1));
ws=wb.addWorksheet('符合性评价记录');ws.addRow(['法规或标准名称','条款号/要求摘要','公司现状与客观证据','判定','差距分析','整改措施','责任部门或责任人','计划完成日期','实际完成日期','状态','逾期天数','验证结果']);selected.forEach(r=>{const e=evalFor(r.id),od=e.due?Math.max(0,-Engine.daysBetween(Engine.cnToday(),e.due)):'';ws.addRow([r.name,r.applicableClauses||r.requirementSummary,e.evidence,e.judgment,e.gap,e.action,e.owner,e.due,'',e.status,od,'']);});sheetHeader(ws,ws.getRow(1));
ws=wb.addWorksheet('法规动态跟踪及官方来源');ws.addRow(['获知日期','信息来源','法规或标准名称','变化类型','原版本','新版本','发布日期','实施日期','实施状态','距实施天数','影响等级','影响评估','应对措施','责任人','完成状态','官方来源']);selected.filter(r=>r.changeType!=='无变化'||r.computedStatus==='即将实施').forEach(r=>ws.addRow([r.lastVerifiedAt,r.sourceName,r.name,r.changeType,(r.replaces||[]).join('、'),r.documentNo,r.publishDate,r.effectiveDate,r.computedStatus,Engine.daysBetween(Engine.cnToday(),r.effectiveDate),'待评估','需要人工评估','核对适用条款并更新内部文件','待指定','未开始',{text:'官方原文',hyperlink:r.sourceUrl}]));sheetHeader(ws,ws.getRow(1));
wb.eachSheet(s=>{s.columns.forEach((c,i)=>c.width=Math.min(42,Math.max(12,i===2?28:16)));s.eachRow(r=>r.eachCell(c=>c.alignment={vertical:'top',wrapText:true}));});const buf=await wb.xlsx.writeBuffer(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));a.download=`EHS合规识别台账_${p.companyName.replace(/[\\/:*?"<>|]/g,'_')}_${Engine.cnToday()}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);show('Excel 已生成，包含四个工作表。');}catch(e){console.error(e);show('Excel 生成失败，请刷新后重试。','error');}}
async function init(){renderChoices();try{const [reg,source]=await Promise.all([fetch('../data/regulations.json').then(r=>{if(!r.ok)throw Error('regulations');return r.json()}),fetch('../data/source-status.json').then(r=>r.json())]);regulations=reg.regulations;$('#verifiedCount').textContent=regulations.filter(r=>r.verificationStatus==='已核验'&&r.complianceEnabled).length;$('#updatedAt').textContent=reg.updatedAt||'待更新';if(source.sources.some(s=>s.status!=='available'))console.info('部分地方来源需要人工复核');restore();}catch(e){$('#initialState').innerHTML='<strong>法规数据正在更新或加载失败</strong><span>请稍后刷新。正式受控库不会被候选数据自动覆盖。</span>';console.error(e);}}
$('#nextBtn').onclick=()=>{if(validateStep())setStep(step+1)};$('#prevBtn').onclick=()=>setStep(step-1);$('#identifyBtn').onclick=run;$('#exampleBtn').onclick=()=>{$('#companyName').value='淄博示例化工有限公司';$('#province').value='山东省';$('#city').value='淄博市';['危险化学品使用企业'].forEach(v=>document.querySelector(`[name=enterpriseTypes][value="${v}"]`).checked=true);['化学原料和化学制品制造'].forEach(v=>document.querySelector(`[name=industries][value="${v}"]`).checked=true);['使用或储存危险化学品','涉及动火作业','涉及受限空间作业','涉及高处作业','涉及临时用电','使用特种设备','存在职业病危害','产生危险废物'].forEach(v=>document.querySelector(`[name=riskTags][value="${v}"]`).checked=true);setStep(2);run();};$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active');});['search','levelFilter','appFilter','statusFilter'].forEach(id=>$('#'+id).oninput=renderLedger);$('#selectAll').onchange=e=>{filtered().forEach(r=>state.selected[r.id]=e.target.checked);save();renderLedger();renderEvaluation();};$('#printBtn').onclick=()=>window.print();$('#exportBtn').onclick=exportExcel;$('#clearBtn').onclick=()=>{if(confirm('确定清除本浏览器保存的企业画像和评价内容吗？')){localStorage.removeItem(KEY);location.reload();}};init();
})();
