(function(root,factory){const api=factory();if(typeof module!=="undefined"&&module.exports)module.exports=api;root.EHSComplianceExport=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
  "use strict";
  const judgments=["待评价","符合","基本符合","不符合","不适用"],conversionStates=["未开始","制度修订中","已转化","不适用"];
  function header(ws,row){row.eachCell(c=>{c.font={bold:true,color:{argb:"FFFFFFFF"}};c.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF1E3A5F"}};c.alignment={vertical:"middle",wrapText:true};});ws.views=[{state:"frozen",ySplit:1}];ws.autoFilter={from:{row:1,column:1},to:{row:1,column:row.cellCount}};ws.pageSetup={orientation:"landscape",fitToPage:true,fitToWidth:1,fitToHeight:0,paperSize:9,margins:{left:.25,right:.25,top:.5,bottom:.5,header:.2,footer:.2}};ws.pageSetup.printTitlesRow="1:1";}
  function listValidation(values){return {type:"list",allowBlank:true,formulae:[`"${values.join(",")}"`],showErrorMessage:true,errorTitle:"请输入有效选项",error:"请从下拉列表中选择。"};}
  function finish(ws,widths){ws.columns.forEach((c,i)=>{c.width=widths[i]||16;c.style={alignment:{vertical:"top",wrapText:true}};});ws.eachRow(r=>r.eachCell(c=>{c.alignment={vertical:"top",wrapText:true};if(c.value instanceof Date)c.numFmt="yyyy-mm-dd";}));}
  function buildWorkbook(ExcelJS,payload){
    const {profile:p,selected,evaluations,meta,today,statusFor,reminderFor,distanceFor}=payload,wb=new ExcelJS.Workbook();wb.creator="EHS-SIL";wb.created=new Date();
    let ws=wb.addWorksheet("企业画像与使用说明");ws.addRow(["字段","内容"]);Object.entries({企业名称:p.companyName,省份:p.province,城市:p.city,企业规模:p.scale,所有制:p.ownership,企业类型:(p.enterpriseTypes||[]).join("、"),行业:(p.industries||[]).join("、"),高风险活动:(p.riskTags||[]).join("、"),危险化学品活动:(p.hazardousActivities||[]).join("、"),危险废物活动:(p.hazardousWasteActivities||[]).join("、"),特种设备:(p.specialEquipmentTypes||[]).join("、"),数据版本:meta.schemaVersion||"1.2.0",受控法规数:meta.verified||0,候选记录数:Math.max(0,(meta.total||0)-(meta.verified||0)),最近核验日期:meta.latestVerifiedAt||"待核验",导出时间:`${today}（中国标准时间）`}).forEach(x=>ws.addRow(x));ws.addRow([]);ws.addRow(["填写说明","先确认适用性，再逐项记录客观证据；基本符合或不符合项必须填写差距、措施、责任人和计划日期。"]);ws.addRow(["版权与使用边界","法规及标准基本信息来源于公开官方渠道；EHS-SIL 对本文件中的原创编排、匹配逻辑、摘要说明和模板设计保留相应权利。本文件仅供会员本人或所在企业内部 EHS 管理使用，不得整表转售、公开传播或作为数据库二次发布。"]);ws.addRow(["免责声明","识别结果仅供管理参考，不构成法律意见，企业仍应结合工艺、设备、物料、许可及属地要求进行最终确认。"]);header(ws,ws.getRow(1));finish(ws,[24,90]);
    ws=wb.addWorksheet("法规识别台账");ws.addRow(["序号","类别层级","法规或标准名称","文号/标准号","状态","发布日期","实施日期","发布机关","适用性结论","匹配原因","适用条款或章节","要求摘要","转化落实情况","主责部门","协同部门","证据要求","下次评审日期","评审提醒","核验状态","官方来源"]);selected.forEach((r,i)=>{const e=evaluations[r.id]||{};ws.addRow([i+1,r.type,r.name,r.documentNo,r.computedStatus,r.publishDate,r.effectiveDate,r.issuingAuthority,r.applicability,(r.reasons||[]).join("；"),r.applicableClauses,r.requirementSummary,e.conversion||"未开始",e.primaryDepartment||(r.suggestedDepartment||[])[0]||"",e.cooperatingDepartments||(r.suggestedDepartment||[]).slice(1).join("、"),e.evidenceRequirement||"需结合适用条款确认",e.reviewDate||"",reminderFor(e.reviewDate),r.verificationStatus,{text:r.sourceName||"官方来源",hyperlink:r.sourceUrl}]);});header(ws,ws.getRow(1));for(let row=2;row<=ws.rowCount;row++){ws.getCell(row,13).dataValidation=listValidation(conversionStates);ws.getCell(row,17).numFmt="yyyy-mm-dd";}if(ws.rowCount>1){ws.addConditionalFormatting({ref:`R2:R${ws.rowCount}`,rules:[{type:"containsText",operator:"containsText",text:"逾期",style:{fill:{type:"pattern",pattern:"solid",bgColor:{argb:"FFFECACA"}}}},{type:"containsText",operator:"containsText",text:"30日内",style:{fill:{type:"pattern",pattern:"solid",bgColor:{argb:"FFFEF3C7"}}}}]});}finish(ws,[8,14,32,18,14,13,13,20,14,36,24,36,16,18,22,28,15,15,14,26]);
    ws=wb.addWorksheet("符合性评价记录");ws.addRow(["法规或标准名称","条款号/要求摘要","公司现状与客观证据","判定","差距分析","整改措施","责任部门或责任人","计划完成日期","实际完成日期","验证结果","自动状态","逾期天数"]);selected.forEach(r=>{const e=evaluations[r.id]||{},status=statusFor(e),overdue=status.startsWith("已逾期")?Number(status.replace(/\D/g,"")):0;ws.addRow([r.name,r.applicableClauses||r.requirementSummary,e.evidence||"",e.judgment||"待评价",e.gap||"",e.action||"",e.owner||"",e.due||"",e.completedAt||"",e.verification||"",status,overdue]);});header(ws,ws.getRow(1));for(let row=2;row<=ws.rowCount;row++){ws.getCell(row,4).dataValidation=listValidation(judgments);for(const col of [8,9])ws.getCell(row,col).numFmt="yyyy-mm-dd";}if(ws.rowCount>1){ws.addConditionalFormatting({ref:`D2:D${ws.rowCount}`,rules:[{type:"containsText",operator:"containsText",text:"不符合",style:{fill:{type:"pattern",pattern:"solid",bgColor:{argb:"FFFECACA"}}}},{type:"containsText",operator:"containsText",text:"基本符合",style:{fill:{type:"pattern",pattern:"solid",bgColor:{argb:"FFFEF3C7"}}}}]});ws.addConditionalFormatting({ref:`L2:L${ws.rowCount}`,rules:[{type:"cellIs",operator:"greaterThan",formulae:[0],style:{fill:{type:"pattern",pattern:"solid",bgColor:{argb:"FFFECACA"}},font:{color:{argb:"FF991B1B"}}}}]});}finish(ws,[32,30,36,14,32,32,20,15,15,26,16,12]);
    ws=wb.addWorksheet("法规动态跟踪及官方来源");ws.addRow(["获知日期","信息来源","法规或标准名称","变化类型","原版本","新版本","发布日期","实施日期","实施状态","实施进度","影响等级","影响评估","应对措施","责任人","完成状态","官方来源"]);selected.filter(r=>r.changeType&&r.changeType!=="无变化"||r.computedStatus==="即将实施").forEach(r=>{const e=evaluations[r.id]||{};ws.addRow([r.lastVerifiedAt,r.sourceName,r.name,r.changeType,(r.replaces||[]).join("、"),r.documentNo,r.publishDate,r.effectiveDate,r.computedStatus,distanceFor(r.effectiveDate),"待评估","需要人工评估","核对适用条款并更新内部文件",e.owner||"待指定",e.conversion||"未开始",{text:"官方原文",hyperlink:r.sourceUrl}]);});header(ws,ws.getRow(1));for(let row=2;row<=ws.rowCount;row++)ws.getCell(row,15).dataValidation=listValidation(conversionStates);finish(ws,[15,18,32,14,20,20,15,15,14,18,12,28,32,18,16,24]);
    return wb;
  }
  return {buildWorkbook};
});
