import {hypotheses,factors,buildReport,excelText,examples} from './pmm-model.mjs';
const $=s=>document.querySelector(s), form=$('#pmm-form');
let report=null, dirty=false;
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const status=text=>{$('#pmm-status').textContent=text;};
function option(host,name,value,title,description){const label=el('label'),input=el('input');input.type='checkbox';input.name=name;input.value=value;const span=el('span',title);if(description)span.append(el('small',description));label.append(input,span);host.append(label);}
factors.forEach(([id,title,description])=>option($('#factor-options'),'factors',id,title,description));
hypotheses.forEach(h=>option($('#hypothesis-options'),'hypotheses',h.id,h.name,h.question));
function invalidate(){dirty=true;report=null;$('#result').hidden=true;status('内容已更新；请生成预览后再导出。当前内容尚未保存到文件。');}
function mode(){return form.elements.mode.value;}
function showMode(){const positive=mode()==='recognition';$('#recognition-fields').hidden=!positive;$('#improvement-fields').hidden=positive;$('#improvement-fields').querySelectorAll('input').forEach(e=>e.disabled=positive);}
function prompts(){const host=$('#prompt-list');host.replaceChildren();for(const h of hypotheses){if(form.querySelector(`[name=hypotheses][value=${h.id}]`).checked){const p=el('p');p.append(el('strong',h.name+'：'),el('span',h.action));host.append(p);}}}
function field(label,key,value='',type='text',options){const wrapper=el('label',label);let input;
  if(options){input=el('select');for(const text of options)input.append(new Option(text,text));}
  else{input=el(type==='textarea'?'textarea':'input');if(type==='textarea')input.rows=2;else input.type=type;input.maxLength=type==='textarea'?1800:120;}
  input.dataset.actionField=key;input.value=value;input.autocomplete='off';wrapper.append(input);return wrapper;}
function renumber(){[...$('#action-list').children].forEach((row,i)=>row.querySelector('h4').textContent=`行动 ${i+1}`);$('#add-action').disabled=$('#action-list').children.length>=12;}
function addAction(value={}){if($('#action-list').children.length>=12){status('最多填写 12 项行动。');return;}const row=el('div',undefined,'pmm-action'),top=el('div',undefined,'pmm-section-heading'),remove=el('button','移除此行动','pmm-button secondary remove-action');remove.type='button';remove.addEventListener('click',()=>{if(confirm('确认移除这项行动？')){row.remove();renumber();invalidate();$('#add-action').focus();}});top.append(el('h4'),remove);row.append(top,field('行动类型','kind',value.kind||'组织改进','select',['组织改进','个人支持','正向认可']),field('具体行动','action',value.action,'textarea'));const meta=el('div',undefined,'pmm-action-meta');meta.append(field('负责人代号','owner',value.owner),field('目标日期','due',value.due,'date'),field('人工记录的状态','status',value.status||'待实施','select',['待实施','实施中','待验证','已验证']));row.append(meta,field('如何验证有效及证据代号','evidence',value.evidence,'textarea'));$('#action-list').append(row);renumber();}
function input(){const fd=new FormData(form),data={};for(const key of ['mode','date','alias','event','view','evidence','context','impact','review'])data[key]=fd.get(key)||'';data.factors=fd.getAll('factors');data.hypotheses=fd.getAll('hypotheses');data.actions=[...$('#action-list').children].map(row=>Object.fromEntries([...row.querySelectorAll('[data-action-field]')].map(f=>[f.dataset.actionField,f.value])));return data;}
function block(host,title,text){const section=el('section',undefined,'pmm-report-block');section.append(el('h3',title),el('p',text||'待补充 / 待核实','pmm-report-text'));host.append(section);}
function render(r){const host=$('#report');host.replaceChildren();host.append(el('p',`${r.version} · ${r.mode} · ${r.date||'日期未填写'} · ${r.alias||'角色未填写'}`),el('p',r.boundary));const warning=el('div',undefined,'pmm-report-warning');warning.append(el('strong',r.missing.length?'建议补充或人工确认':'记录字段已填写，内容仍需人工复核'));const list=el('ul');for(const value of r.missing)list.append(el('li',value));warning.append(list);host.append(warning);
  for(const [label,key] of [['观察事实','event'],['当事人视角','view'],['依据与待核实信息','evidence'],['工作情境与支持','context']])block(host,label,r[key]);
  block(host,'关注的工作因素',r.factors.join('；'));
  if(r.mode==='正向认可')block(host,'具体价值与可复制条件',r.impact);else for(const h of r.hypotheses)block(host,'待核实解释：'+h.name,h.question+'\n参考改进方向：'+h.action);
  r.actions.forEach((a,i)=>block(host,`行动 ${i+1} · ${a.kind}`,`${a.action}\n负责人代号：${a.owner||'待指定'} ｜ 目标日期：${a.due||'待安排'} ｜ 状态：${a.status}\n验证依据：${a.evidence||'待补充'}`));
  block(host,'复核与跟进安排',r.review);host.append(el('p','仅在当前浏览器生成。请核对并脱敏后分享；不要将本文作为人员处分或作业批准依据。'));$('#result').hidden=false;$('#result-title').focus();}
form.addEventListener('input',()=>{invalidate();showMode();prompts();});
form.addEventListener('change',()=>{invalidate();showMode();prompts();});
form.addEventListener('submit',event=>{event.preventDefault();report=buildReport(input());render(report);status('预览已生成；提示仅检查记录是否有待补充项，不评价人员或安全水平。');});
$('#add-action').addEventListener('click',()=>{addAction();invalidate();$('#action-list').lastElementChild?.querySelector('textarea')?.focus();});
$('#load-example').addEventListener('click',()=>{if(dirty&&!confirm('用虚构教学示例替换当前内容？尚未导出的内容将丢失。'))return;const example=examples[mode()];form.reset();form.elements.mode.value=example.mode;for(const [key,value] of Object.entries(example)){if(typeof value==='string'&&form.elements[key])form.elements[key].value=value;}for(const name of ['hypotheses','factors'])for(const value of example[name]||[])form.querySelector(`[name=${name}][value=${value}]`).checked=true;$('#action-list').replaceChildren();example.actions.forEach(addAction);showMode();prompts();invalidate();status('已载入虚构教学示例，不代表真实访谈或现场结果。日期与负责人须自行复核。');form.elements.event.focus();});
$('#clear-record').addEventListener('click',()=>{if(!confirm('清空本页所有输入？已下载文件不会被删除。'))return;form.reset();$('#action-list').replaceChildren();addAction();showMode();prompts();report=null;dirty=false;$('#result').hidden=true;status('本页输入已清空；请自行管理已下载的文件。');});
$('#print-record').addEventListener('click',()=>{if(report)window.print();});
$('#export-excel').addEventListener('click',async()=>{if(!report)return;const button=$('#export-excel');button.disabled=true;const snapshot=report;try{if(!window.ExcelJS)throw new Error('export unavailable');const wb=new window.ExcelJS.Workbook();wb.creator='EHS-SIL';wb.created=new Date();
  const rows=[['PMM 渐进式激励管理｜对话记录草稿','内容'],['版本',snapshot.version],['专业边界',snapshot.boundary],['对话方向',snapshot.mode],['日期',snapshot.date],['角色或代号',snapshot.alias],['观察事实',snapshot.event],['当事人视角',snapshot.view],['依据与待核实信息',snapshot.evidence],['工作情境与支持',snapshot.context],['工作因素',snapshot.factors.join('；')],['正向行为的价值',snapshot.impact],['复核与跟进',snapshot.review],['建议补充或人工确认',snapshot.missing.join('；')||'字段已填写，内容仍需人工复核']];
  const sheets=[['对话记录',rows,[30,95]],['待核实解释',[['解释（非定性）','对话问题','参考改进方向'],...snapshot.hypotheses.map(h=>[h.name,h.question,h.action])],[38,55,80]],['行动跟进',[['类型','具体行动','负责人代号','目标日期','验证依据','状态（人工填写）'],...snapshot.actions.map(a=>[a.kind,a.action,a.owner,a.due,a.evidence,a.status])],[18,55,20,18,55,22]],['使用说明',[['项目','说明'],['隐私','本文件可能包含你输入的敏感信息，请控制访问、按企业规则保管，分享前再次脱敏。'],['使用范围',snapshot.boundary],['专业参考','https://ehs-sil.com/tools/pmm-coach.html#method'],['程序提醒','记录草稿不替代事件调查。严重行为疑虑由授权管理者与人力资源部门独立复核。']],[26,100]]];
  for(const [name,data,widths] of sheets){const sheet=wb.addWorksheet(name);sheet.columns=widths.map(width=>({width}));for(const row of data)sheet.addRow(row.map(excelText));sheet.eachRow((row,i)=>{row.alignment={vertical:'top',wrapText:true};row.font={name:'Arial',size:11};row.height=i===1?30:Math.min(220,Math.max(32,Math.ceil(Math.max(...row.values.slice(1).map(x=>String(x||'').length))/38)*17));if(i===1){row.font={name:'Arial',size:11,bold:true,color:{argb:'FFFFFFFF'}};row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF174D50'}};}});sheet.views=[{state:'frozen',ySplit:1}];sheet.pageSetup={paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0};}
  const blob=new Blob([await wb.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='EHS-SIL_PMM_对话记录.xlsx';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status('已生成 Excel 下载。请检查内容并妥善保管；本页仍不会保存输入。');
}catch{status('Excel 导出未成功。请重试，或先使用打印 / 存为 PDF 保存记录。');}finally{button.disabled=false;}});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
addAction();showMode();
