import assert from "node:assert/strict";import {createRequire} from "node:module";const require=createRequire(import.meta.url),ExcelJS=require("../vendor/exceljs.min.js"),Exporter=require("../js/compliance-export.js"),Workflow=require("../js/compliance-workflow.js"),Engine=require("../js/compliance-engine.js");
const regulation={id:"REG-TEST",type:"法律",name:"测试法规",documentNo:"测试文号",computedStatus:"现行有效",publishDate:"2026-01-01",effectiveDate:"2026-02-01",issuingAuthority:"测试机关",applicability:"建议复核",reasons:["测试规则"],applicableClauses:"第二条",requirementSummary:"测试摘要",suggestedDepartment:["生产部门","EHS部门"],verificationStatus:"待复核",sourceName:"官方来源",sourceUrl:"https://example.gov.cn/detail",changeType:"新增",replaces:[],lastVerifiedAt:"2026-08-01"};
const evaluations={"REG-TEST":{judgment:"不符合",gap:"存在差距",action:"完成整改",owner:"张三",due:"2026-07-01",conversion:"制度修订中",reviewDate:"2026-08-15"}};
const statusFor=e=>Workflow.evaluationStatus(e,"2026-08-01",Engine.daysBetween),wb=Exporter.buildWorkbook(ExcelJS,{profile:{companyName:"测试企业",province:"江苏省",enterpriseTypes:["机械制造企业"]},selected:[regulation],evaluations,meta:{schemaVersion:"1.2.0",total:100,verified:6,latestVerifiedAt:"2026-07-31"},today:"2026-08-01",statusFor,reminderFor:d=>Engine.reviewReminder(d,"2026-08-01"),distanceFor:d=>Engine.implementationDistanceLabel(d,"2026-08-01")});
const buf=await wb.xlsx.writeBuffer();assert.ok(buf.length>8000);assert.equal(Buffer.from(buf).subarray(0,2).toString(),"PK");const reread=new ExcelJS.Workbook();await reread.xlsx.load(buf);assert.deepEqual(reread.worksheets.map(s=>s.name),["企业画像与使用说明","法规识别台账","符合性评价记录","法规动态跟踪及官方来源"]);const ledger=reread.getWorksheet("法规识别台账"),evaluation=reread.getWorksheet("符合性评价记录");assert.equal(ledger.getCell("T2").value.hyperlink,"https://example.gov.cn/detail");assert.equal(ledger.getCell("M2").dataValidation.type,"list");assert.equal(evaluation.getCell("D2").dataValidation.type,"list");assert.equal(evaluation.getCell("K2").value,"已逾期 31 天");assert.equal(evaluation.pageSetup.orientation,"landscape");assert.equal(evaluation.pageSetup.fitToWidth,1);console.log(JSON.stringify({status:"PASS",bytes:buf.length,sheets:reread.worksheets.length,validations:2}));

// V1.6 exports guidance without fabricating the enterprise's actual evidence.
const guided={...regulation,id:"REG-GUIDED",scopeApplicability:"画像范围匹配",sourceVerification:"版本/来源尚待核验",computedStatus:"待核实",missingFacts:["排放VOCs"],evidenceRequirement:"检测报告与台账",suggestedAction:"核对排口并建立台账",evaluationDraft:"已生成检查项；履行情况需以实际证据为准",matchedClauses:[{id:"C-1",reference:"第二条",summary:"保留检测记录"},{id:"C-2",reference:"第六条",summary:"开展设施检查"}]};
const guidedProfile={companyName:"测试企业",province:"江苏省",enterpriseTypes:["机械制造企业"],specialOperationTypes:["涉及高处作业"],industryAttributes:["化工属性"],managementCommitments:["自愿采纳ISO 14001"],environmentalActivities:["排放工业废水"],regulatoryAttributes:["建设项目新改扩建"],workplaceActivities:["涉及有限空间"],answers:{排放VOCs:"no",工作场所粉尘:"yes",地下水取水:"unknown"}};
const fresh={...guided,id:"REG-FRESH"},history={...guided,id:"REG-HISTORY"};
const enriched=Exporter.buildWorkbook(ExcelJS,{profile:guidedProfile,selected:[guided,fresh,history],evaluations:{"REG-GUIDED":{judgment:"符合",needsReassessment:true,checks:{"C-1":{state:"provided",note:"检测报告 2026-09-01"},"C-2":{state:"provided",note:""},"OLD":{state:"missing",note:"历史证据缺项"}}},"REG-HISTORY":{evidence:"用户提供的实际记录",evidenceRequirement:"用户修订证据要求",checks:{"C-1":{state:"missing",note:"缺少报告"}}}},meta:{schemaVersion:"1.6.0",total:102,verified:30,latestVerifiedAt:"2026-09-11"},today:"2026-09-11",statusFor,reminderFor:d=>Engine.reviewReminder(d,"2026-09-11"),distanceFor:d=>Engine.implementationDistanceLabel(d,"2026-09-11")});
const enrichedBuffer=await enriched.xlsx.writeBuffer(),enrichedRead=new ExcelJS.Workbook();await enrichedRead.xlsx.load(enrichedBuffer);
assert.equal(enrichedRead.worksheets.length,4);
const profileRows=new Map(enrichedRead.getWorksheet("企业画像与使用说明").getRows(2,40).filter(Boolean).map(r=>[r.getCell(1).value,r.getCell(2).value]));
for(const [label,value] of Object.entries({特殊作业详情:"涉及高处作业",行业属性:"化工属性",自愿采纳的管理标准:"自愿采纳ISO 14001",环境活动:"排放工业废水",监管与项目属性:"建设项目新改扩建",工作场所活动:"涉及有限空间",数据版本:"1.6.0","画像追问：排放VOCs":"否","画像追问：工作场所粉尘":"是","画像追问：地下水取水":"尚不确定"}))assert.equal(profileRows.get(label),value,label);
const richLedger=enrichedRead.getWorksheet("法规识别台账"),richEvaluation=enrichedRead.getWorksheet("符合性评价记录");
assert.equal(richLedger.getCell("E2").value,"待核实");assert.equal(richLedger.getCell("S2").value,"版本/来源尚待核验");assert.equal(richLedger.getCell("U2").value,"画像范围匹配");assert.equal(richLedger.getCell("V2").value,"排放VOCs");assert.equal(richLedger.getCell("W2").value,"核对排口并建立台账");assert.match(richLedger.getCell("X2").value,/版本已变，需重评/);
assert.equal(richLedger.getCell("P2").value,"检测报告与台账");assert.equal(richLedger.getCell("P4").value,"用户修订证据要求");
assert.equal(richEvaluation.getCell("B2").value,"第二条：保留检测记录\n第六条：开展设施检查");assert.equal(richEvaluation.getCell("C2").value,"");assert.equal(richEvaluation.getCell("K2").value,"版本已变，需重评");assert.equal(richEvaluation.getCell("D3").value,"待评价");assert.equal(richEvaluation.getCell("C3").value,"");assert.equal(richEvaluation.getCell("C4").value,"用户提供的实际记录");
assert.match(richEvaluation.getCell("M2").value,/履行情况需以实际证据为准/);assert.match(richEvaluation.getCell("N2").value,/已选择提供，但缺少证据索引/);assert.match(richEvaluation.getCell("O2").value,/检测报告 2026-09-01/);assert.match(richEvaluation.getCell("O2").value,/历史\/未匹配条款 OLD：历史证据缺项/);assert.match(richEvaluation.getCell("N4").value,/已发现缺项/);
const noMeta=Exporter.buildWorkbook(ExcelJS,{profile:{},selected:[],evaluations:{},today:"2026-09-11",statusFor,reminderFor:()=>"",distanceFor:()=>""});
assert.equal(noMeta.getWorksheet("企业画像与使用说明").getRows(1,30).find(r=>r.getCell(1).value==="数据版本").getCell(2).value,"未提供");
console.log(JSON.stringify({status:"PASS",v16Bytes:enrichedBuffer.length,ledgerColumns:richLedger.columnCount,evaluationColumns:richEvaluation.columnCount,actualEvidenceNotFabricated:true,reassessmentPreserved:true}));
