import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
const code=fs.readFileSync(new URL("../js/compliance-engine.js",import.meta.url),"utf8"),sandbox={Intl,Date,console};sandbox.globalThis=sandbox;vm.runInNewContext(code,sandbox);const E=sandbox.EHSComplianceEngine;
const read=p=>JSON.parse(fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8"));
const data=[...read("data/compliance/laws.v1.json").records,...read("data/compliance/candidates.v1.json").records],rules=read("data/compliance/rules.v1.json").rules;
const sd={companyName:"测试化工",province:"山东省",city:"淄博市",enterpriseTypes:["危险化学品使用企业"],industries:["化学原料和化学制品制造"],riskTags:["涉及动火作业","涉及受限空间作业","存在职业病危害"],hazardousActivities:["危化品使用","危化品储存"],hazardousWasteActivities:["危废产生","危废暂存"],specialEquipmentTypes:["压力容器"],industryAttributes:["化工属性"]};
const js={companyName:"测试机械",province:"江苏省",city:"苏州市",enterpriseTypes:["机械制造企业"],industries:["通用设备制造"],specialEquipmentTypes:["场（厂）内专用机动车辆"]};
const a=E.identify(data,sd,{rules,today:"2026-08-01"}),b=E.identify(data,js,{rules,today:"2026-08-01"});
assert.ok(a.some(r=>r.id==="REG-SD-001"&&r.applicability==="明确适用"));
assert.ok(!b.some(r=>r.id==="REG-SD-001"),"江苏画像不得匹配山东地方要求");
assert.ok(a.some(r=>r.name==="中华人民共和国危险化学品安全法"));
assert.ok(a.every(r=>r.reasons.length>0));
assert.ok(a.filter(r=>r.verificationStatus!=="已核验").every(r=>r.applicability==="建议复核"));
assert.equal(E.reviewReminder("2026-07-30","2026-07-31"),"已逾期");assert.equal(E.reviewReminder("2026-08-30","2026-07-31"),"30日内到期");assert.equal(E.reviewReminder("2026-10-29","2026-07-31"),"即将评审");
console.log(JSON.stringify({status:"PASS",shandong:a.length,jiangsu:b.length,localIsolation:true}));
