import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url),E=require('../js/compliance-engine.js'),G=require('../js/compliance-guidance.js'),W=require('../js/compliance-workflow.js');
const r={id:'UNIT',name:'回归测试用规则',documentNo:'TEST',type:'法律',levelRank:1,regions:['全国'],status:'现行有效',effectiveDate:'2026-01-01',lastVerifiedAt:'2026-09-11',verificationStatus:'已核验',complianceEnabled:true,clauses:[{id:'CORE',reference:'第1条',summary:'通用义务',whenAny:[],whenAll:[],evidence:['职责记录'],action:'建立职责'},{id:'WATER',reference:'第2条',summary:'工业废水义务',whenAny:['排放工业废水'],whenAll:[],evidence:['废水流程图'],action:'梳理水流向'}]};
const rule={regulationId:'UNIT',includeAll:['生产经营单位'],includeAny:[],reviewWhen:[],excludeAny:[],applicability:'mandatory',explanationTemplate:'通用主体责任'};
const identify=(profile={},extra={})=>E.identify([r],profile,{rules:[rule],today:'2026-09-11',...extra})[0];
assert.equal(identify().matchedClauses.length,1);
assert.equal(identify().pendingClauses.length,1);
assert.ok(identify().missingFacts.includes('排放工业废水'));
assert.equal(identify({answers:{排放工业废水:'no'}}).pendingClauses.length,0);
assert.equal(identify({answers:{排放工业废水:'yes'}}).matchedClauses.length,2);
assert.equal(identify({environmentalActivities:['排放工业废水']}).matchedClauses.length,2);
assert.equal(identify().applicability,'明确适用');
assert.match(identify().evaluationDraft,/不自动判定符合/);
assert.equal(E.implementationStatus({...r,verificationStatus:'待复核'},'2026-09-11'),'待核实');
assert.equal(E.implementationStatus({...r,effectiveDate:'2026-10-01'},'2026-09-11'),'即将实施');
assert.equal(E.identify([r],{},{rules:[{...rule,status:'disabled'}]}).length,0);
assert.equal(E.implementationStatus({...r,supersededBy:{effectiveDate:'2026-08-15'}},'2026-08-14'),'现行有效');
assert.equal(E.implementationStatus({...r,supersededBy:{effectiveDate:'2026-08-15'}},'2026-08-15'),'已废止');
const narrow={...rule,includeAll:[],includeAny:['排放工业废水'],reviewWhen:['产生废水']};
assert.equal(identify({riskTags:['产生废水']},{rules:[narrow]}).applicability,'建议复核');
assert.equal(E.identify([r],{riskTags:['产生废水'],answers:{排放工业废水:'no'}},{rules:[narrow]}).length,0);
const pending=E.identify([{...r,verificationStatus:'待复核'}],{},{rules:[rule]})[0];
assert.equal(pending.scopeApplicability,'画像范围匹配');
assert.equal(pending.applicability,'建议复核');
assert.match(pending.sourceVerification,/待核验/);
assert.equal(G.evidenceProgress(identify(),{CORE:{state:'provided',note:''}}).documented,0);
assert.equal(G.evidenceProgress(identify(),{CORE:{state:'provided',note:'职责文件2026'}}).documented,1);
assert.match(G.evidenceProgress(identify(),{CORE:{state:'provided',note:'职责文件2026'}}).label,/非合规结论/);
assert.equal(G.evidenceProgress(identify(),{CORE:{state:'missing'}}).missing,1);
assert.throws(()=>G.mergeCatalog([],[],[{schemaVersion:'1.6.0',records:[r,r]}]),/重复/);
assert.ok(E.profileFacts({enterpriseTypes:['机械制造企业']}).has('工贸企业'));
assert.ok(!E.profileFacts({enterpriseTypes:['危险化学品生产企业']}).has('工贸企业'));
assert.ok(E.profileFacts({hazardousActivities:['危化品经营','危化品储存']}).has('危化品经营（带储存）'));
assert.ok(!E.profileFacts({hazardousActivities:['危化品经营']}).has('危化品经营（带储存）'));
assert.ok(W.requiredMissing({judgment:'符合'}).includes('符合判定的客观证据'));
assert.ok(W.requiredMissing({judgment:'不适用'}).includes('不适用的范围依据'));
const project=W.createProject({profile:{companyName:'回归测试',answers:{排放工业废水:'no'},environmentalActivities:['排放VOCs']},selected:{UNIT:true},evaluations:{UNIT:{checks:{CORE:{state:'provided',note:'索引'}}}}});
assert.deepEqual(W.validateProject(JSON.parse(JSON.stringify(project))).profile.answers,{排放工业废水:'no'});
assert.throws(()=>W.validateProject({...project,profile:{answers:{任意条件:'maybe'}}}),/回答无效/);
assert.throws(()=>W.validateProject({...project,profile:{riskTags:'不是数组'}}),/画像字段无效/);
assert.throws(()=>W.validateProject(JSON.parse(JSON.stringify(project).replace('"profile":{','"profile":{"__proto__":{},'))),/不安全/);
const app=fs.readFileSync(new URL('../js/compliance-app.js',import.meta.url),'utf8');
assert.doesNotMatch(app,/if\(legacyEnvironment\)p\.riskTags\.push/);
assert.doesNotMatch(app,/meta:\{\.\.\.databaseMeta,schemaVersion:'1\.2\.0'\}/);
console.log(JSON.stringify({status:'PASS',suite:'v1.6 tri-state, evidence, dates, migration and import safety'}));
