import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRecord,createItem,createDemo,evaluate,updateRecord,transition,refreshExpiry,applySuggestions,copyRecord,riskScore} from '../js/moc-engine.mjs';
const names={categories:'categories',impactPrompts:'impact-prompts',criticalTriggers:'critical-triggers',documentMap:'document-map',methodRouting:'method-routing',riskMatrix:'risk-matrix.default',demoCase:'demo-case',references:'references'};
const config=Object.fromEntries(Object.entries(names).map(([key,name])=>[key,JSON.parse(readFileSync(new URL(`../data/moc/${name}.json`,import.meta.url),'utf8'))]));
const NOW='2026-09-12T04:00:00.000Z';
function completeRecord() {
  let r=createRecord(config,NOW);
  r.meta.title='虚构程序变更';Object.assign(r.changeSummary,{area:'示例区域',before:'原流程',after:'更新流程',reason:'改善交接',expectedResult:'职责清楚',plannedStart:'2026-09-20',applicant:'申请角色',owner:'负责角色',technicalBasis:'已完成技术边界核查'});
  r.screening.replacementComparisons.forEach(item=>Object.assign(item,{result:'same',evidence:'核查资料已确认完全相同'}));Object.assign(r.screening,{rationale:'除文控更新外属性保持，保存依据并继续完成评审',replacementConfirmedBy:'授权角色',replacementConfirmedAt:'2026-09-12'});
  Object.assign(r.classification,{categories:['procedure'],scope:'department',confirmedLevel:'general'});r.impactDomains.forEach(item=>item.status='none');
  r.riskItems=[{...createItem('risk'),scenario:'程序执行偏差',cause:'内容交接不足',consequence:'误操作',affected:'操作人员',existingControls:'既有操作确认',initialLikelihood:2,initialSeverity:{people:3,environment:2,asset:2,reputation:1},additionalMeasures:'完成交接和核查',owner:'负责角色',due:'2026-09-20',status:'done',evidence:'确认清单',residualLikelihood:1,residualSeverity:3,acceptanceBy:'接受角色',acceptanceNote:'核查残余风险并接受'}];
  Object.assign(r.pssr,{required:false,rationale:'仅文件说明调整，未改变启动准备',confirmedBy:'专业确认角色',confirmedAt:'2026-09-12',status:'not_required'});r.implementation.plan='按批准的清单修订并验证';
  r=applySuggestions(r,config,NOW);
  r.documents.forEach(item=>Object.assign(item,{owner:'文件负责角色',due:'2026-09-20',status:'done',evidence:'更新版本',approvedBy:'批准角色'}));
  r.training.forEach(item=>Object.assign(item,{content:'变更内容与操作边界',method:'现场沟通',date:'2026-09-12',trainer:'培训角色',status:'done',evidence:'签到与确认'}));
  r.approvals.forEach(item=>Object.assign(item,{name:'评审角色',opinion:'已核查对应职责范围',conclusion:'approved',date:'2026-09-12',evidence:'线下批准记录',version:r.meta.version}));
  Object.assign(r.verification,{scopeMatches:'yes',effectsAchieved:'yes',newRisks:'no',evidence:'运行观察及检查记录',verifiedBy:'验证角色',verifiedAt:'2026-09-22',closeReason:'所有措施完成且效果经验证'});
  return r;
}
function approved(r=completeRecord()) {for(const state of ['assessed','pending_approval','approved'])r=transition(r,state,'记录角色','记录当前阶段证据',config,NOW);return r;}
function startup(r=approved()) {
  r=transition(r,'implementing','记录角色','按批准方案实施',config,NOW);
  for(const [path,value]of Object.entries({startupAuthorizedBy:'授权角色',startupAuthorizedAt:'2026-09-21',startupAuthorizationEvidence:'线下投用批准记录'}))r=updateRecord(r,`implementation.${path}`,value,'记录角色',config,NOW);
  return r;
}

test('T01 equal comparisons only advise replacement and do not close or mutate',()=>{const r=completeRecord(),snapshot=JSON.stringify(r),v=evaluate(r,config,NOW);assert.equal(v.replacement.code,'possible_replacement');assert.equal(r.meta.status,'draft');assert.equal(JSON.stringify(r),snapshot);assert.equal(v.approvalBlockers.length,0);r.screening.replacementComparisons=[];assert.equal(evaluate(r,config,NOW).replacement.code,'needs_review');});
test('T02 neutral pump example changes seal/power and routes equipment/electrical checks',()=>{const r=createDemo(config,NOW),v=evaluate(r,config,NOW);assert.equal(v.replacement.code,'moc');assert.ok(v.effectiveCategories.includes('equipment'));assert.ok(v.effectiveCategories.includes('electrical'));assert.equal(r.riskItems.length,3);assert.ok(v.suggestedDocuments.some(x=>x.id==='equipment_data'));assert.equal(v.pssrRecommendation.required,true);});
test('T03 DCS logic comparison alone triggers important change and PSSR',()=>{const r=completeRecord();r.screening.replacementComparisons.find(x=>x.id==='logic').result='changed';const v=evaluate(r,config,NOW);assert.equal(v.level.code,'important');assert.equal(v.pssrRecommendation.required,true);assert.ok(v.effectiveCategories.includes('instrument'));assert.ok(v.effectiveCategories.includes('process'));});
test('T04 temporary change requires expiry/restoration; expiry latches and cannot be bypassed by date',()=>{let r=completeRecord();r.screening.durationType='temporary';assert.ok(evaluate(r,config,NOW).approvalBlockers.some(x=>x.includes('到期日和恢复方案')));r.screening.temporaryExpiry='2026-09-11';r.screening.restorationPlan='隔离后恢复并验证';r=refreshExpiry(r,config,NOW);assert.equal(r.meta.status,'expired');assert.ok(r.screening.expiredAt);assert.throws(()=>updateRecord(r,'screening.temporaryExpiry','2027-01-01','记录角色',config,NOW),/不能直接改日期/);assert.throws(()=>updateRecord(r,'screening.durationType','permanent','记录角色',config,NOW),/不能直接改日期/);assert.throws(()=>transition(r,'reopened','记录角色','重新开启',config,NOW),/仍过期/);});
test('expiry uses Asia/Shanghai midnight and carries valid new professional review to reassessment',()=>{let r=completeRecord();Object.assign(r.screening,{durationType:'temporary',temporaryExpiry:'2026-09-12',restorationPlan:'恢复核查'});assert.equal(evaluate(r,config,'2026-09-12T15:59:59Z').expired,false);assert.equal(evaluate(r,config,'2026-09-12T16:00:00Z').expired,true);r=refreshExpiry(r,config,'2026-09-12T16:00:00Z');for(const [key,value]of Object.entries({by:'重新评审角色',date:'2026-09-13',evidence:'新的专业评审批准依据',newExpiry:'2026-10-01'}))r=updateRecord(r,`screening.expiryReview.${key}`,value,'记录角色',config,'2026-09-12T16:00:00Z');assert.equal(r.meta.status,'assessed');assert.equal(r.meta.version,2);assert.equal(r.screening.temporaryExpiry,'2026-10-01');assert.equal(r.screening.expiredAt,'');assert.equal(r.meta.approvedVersion,0);});
test('T05 emergency safety bypass needs controls and prior authorization and cannot skip workflow',()=>{const r=completeRecord();r.screening.emergency=true;r.classification.triggers=['safety_function'];const v=evaluate(r,config,NOW);assert.equal(v.level.code,'important');assert.ok(v.approvalBlockers.some(x=>x.includes('最低控制')));assert.ok(v.approvalBlockers.some(x=>x.includes('实施前授权')));assert.ok(v.warnings.some(x=>x.includes('48 小时')));assert.throws(()=>transition(r,'implementing','记录角色','紧急',config,NOW),/跳过/);});
test('T06 key safety role adjustment asks for capabilities/docs and manual PSSR judgment',()=>{const r=completeRecord();r.classification.categories=['organization'];r.classification.triggers=['key_organization'];const v=evaluate(r,config,NOW);assert.equal(v.level.code,'important');assert.equal(v.pssrRecommendation.required,null);assert.ok(v.suggestedDocuments.some(x=>x.id==='responsibility'));assert.ok(v.suggestedTraining.some(x=>x.id==='affected_roles'));assert.ok(v.effectiveImpacts.includes('organization'));});
test('T07 new chemical demands SDS and health/environment/fire/compliance domains',()=>{const r=completeRecord();r.classification.triggers=['chemical_change'];const v=evaluate(r,config,NOW);assert.equal(v.replacement.code,'moc');assert.ok(v.suggestedDocuments.some(x=>x.id==='sds'));for(const id of ['health','environment','emergency','compliance'])assert.ok(v.effectiveImpacts.includes(id));assert.ok(v.approvalBlockers.some(x=>x.includes('与关键触发器冲突')));});
test('T08 changing approved scope/plan/key measures/approval invalidates version and authorization',()=>{for(const path of ['changeSummary.after','implementation.plan','riskItems.0.additionalMeasures','documents.0.title','training.0.content','approvals.0.name','approvals.0.evidence']){const r=approved(),changed=updateRecord(r,path,'新的评审内容','记录角色',config,NOW);assert.equal(changed.meta.version,2,path);assert.equal(changed.meta.status,'assessed',path);assert.equal(changed.meta.approvedVersion,0,path);assert.ok(changed.approvals.every(item=>item.conclusion==='pending'));assert.equal(r.meta.version,1);}const r=approved();r.approvals[0].conclusion='rejected';assert.ok(evaluate(r,config,NOW).startupBlockers.some(x=>x.includes('退回意见')));});
test('T09 one open before-startup action blocks readiness; safety critical cannot defer',()=>{let r=approved();r.actions.push({...createItem('action'),title:'投用前验证',owner:'责任角色',due:'2026-09-20',evidenceRequirement:'验证记录'});r.meta.status='implementing';assert.throws(()=>transition(r,'ready_for_startup','记录角色','准备投用',config,NOW),/行动|授权/);assert.ok(evaluate(r,config,NOW).startupBlockers.some(x=>x.includes('投用前行动')));assert.throws(()=>updateRecord(r,'actions.0.gate','after_startup','记录角色',config,NOW),/安全关键/);r.actions[0].gate='after_startup';assert.ok(evaluate(r,config,NOW).approvalBlockers.some(x=>x.includes('安全关键')));});
test('T10 required unpassed PSSR prevents recording startup authorization',()=>{const r=approved();Object.assign(r.pssr,{required:true,status:'in_progress'});assert.throws(()=>updateRecord(r,'implementation.startupAuthorizedBy','授权角色','记录角色',config,NOW),/PSSR/);r.pssr.required=false;r.pssr.status='not_required';r.pssr.confirmedBy='';assert.ok(evaluate(r,config,NOW).approvalBlockers.some(x=>x.includes('专业确认人')));});
test('T11 temporary permanent conversion cannot close without another approved review',()=>{let r=startup();Object.assign(r.screening,{durationType:'temporary',temporaryExpiry:'2026-10-01',restorationPlan:'恢复方案'});r.verification.temporaryOutcome='permanent';assert.ok(evaluate(r,config,NOW).closeBlockers.some(x=>x.includes('另一评审编号')));r.verification.permanentReviewId=r.meta.id;r.verification.permanentReviewEvidence='批准记录';assert.ok(evaluate(r,config,NOW).closeBlockers.some(x=>x.includes('另一评审编号')));});
test('empty risk and missing generated documents/training/roles cannot pass approval',()=>{const r=completeRecord();r.riskItems=[];r.documents=[];r.training=[];r.approvals=[];const blocks=evaluate(r,config,NOW).approvalBlockers;for(const text of ['风险情景','必需文件','培训／沟通计划','评审角色'])assert.ok(blocks.some(item=>item.includes(text)),text);});
test('extreme risk cannot be accepted and high residual risk requires professional review',()=>{const r=completeRecord(),risk=r.riskItems[0];risk.residualLikelihood=5;risk.residualSeverity=5;assert.ok(evaluate(r,config,NOW).approvalBlockers.some(x=>x.includes('极高残余风险')));risk.residualLikelihood=3;risk.residualSeverity=4;assert.ok(evaluate(r,config,NOW).approvalBlockers.some(x=>x.includes('高残余风险需专业')));risk.professionalReview='复核结论';assert.ok(!evaluate(r,config,NOW).approvalBlockers.some(x=>x.includes('高残余风险需专业')));risk.residualLikelihood='';assert.ok(evaluate(r,config,NOW).approvalBlockers.some(x=>x.includes('残余风险未完成')));assert.equal(riskScore(1,{},config.riskMatrix),null);});
test('complete lifecycle closes only after evidence and records audit; reopening invalidates authority',()=>{let r=startup();for(const state of ['ready_for_startup','in_service','verification_due','closed'])r=transition(r,state,'记录角色','线下记录已复核',config,NOW);assert.equal(r.meta.status,'closed');assert.equal(r.meta.approvedVersion,r.meta.version);assert.throws(()=>updateRecord(r,'meta.title','直接修改','记录角色',config,NOW),/不能直接修改/);assert.throws(()=>applySuggestions(r,config,NOW),/不能直接生成/);const reopened=transition(r,'reopened','记录角色','发现新偏差',config,NOW);assert.equal(reopened.meta.version,2);assert.equal(reopened.meta.approvedVersion,0);assert.equal(reopened.implementation.startupAuthorizedBy,'');assert.ok(reopened.auditTrail.some(x=>x.action==='status:closed->reopened'));});
test('suggestions are additive/idempotent and completion updates do not invalidate approval',()=>{const r=approved(),again=applySuggestions(r,config,NOW);assert.equal(again,r);const updated=updateRecord(r,'documents.0.evidence','新增验证记录','记录角色',config,NOW);assert.equal(updated.meta.version,1);assert.equal(updated.meta.status,'approved');});
test('copy is a distinct draft with no inherited current approvals, startup or completion authority',()=>{const original=startup(),copy=copyRecord(original,config,NOW);assert.notEqual(copy.meta.id,original.meta.id);assert.equal(copy.meta.status,'draft');assert.equal(copy.meta.version,1);assert.equal(copy.meta.approvedVersion,0);assert.equal(copy.implementation.startupAuthorizedBy,'');assert.ok(copy.riskItems.every(item=>item.status==='open'&&!item.evidence));});

test('whole item-list replacement validates schemas and cannot silently downgrade approved critical controls',()=>{const r=approved();const risks=structuredClone(r.riskItems);risks[0].gate='after_startup';risks[0].safetyCritical=false;assert.throws(()=>updateRecord(r,'riskItems',risks,'记录人',config,NOW),/安全关键/);assert.throws(()=>updateRecord(r,'actions',[{}],'记录人',config,NOW),/字段/);assert.throws(()=>updateRecord(r,'classification.categories',['not-real'],'记录人',config,NOW),/分类列表/);assert.throws(()=>updateRecord(r,'riskItems.0.status','invented','记录人',config,NOW),/无效选项/);assert.throws(()=>updateRecord(r,'riskItems.0.initialLikelihood',99,'记录人',config,NOW),/风险评分/);const changed=structuredClone(r.riskItems);changed[0].additionalMeasures='新的控制措施';const updated=updateRecord(r,'riskItems',changed,'记录人',config,NOW);assert.equal(updated.meta.version,2);assert.equal(updated.meta.approvedVersion,0);});
